title: "Operating Systems 2021-1 (OS211)"
description: "Hello"
author: "Jafar Abdurrohman"
copyright: "2021-2021"
address: "Tangsel"
sitemap: "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb: "https://abdurrohmanjafar.github.io/test/"
urlgithub: "https://github.com/abdurrohmanjafar/test/"
urlghpage: "https://abdurrohmanjafar.github.io/test/"
keywords: "jekyll, testing"
github: [metadata]